### ISSUE TITLE
missing dependency for "UFONet"

### ISSUE THREAD

**Issue by remo7777** [Gameye98/Lazymux#1]
for pycurl need  `libcurl` package

pycrypto need which dependency  .... idk 

and error for GeoIP ..
`py_GeoIP.c:23:10: fatal error: 'GeoIP.h' file not
      found
#include "GeoIP.h"
         ^~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'aarch64-linux-android-clang' failed with exit status 1`

**Comment by Gameye98** [comment]
sorry for the issue, I replaced UFOnetinto BlackBox

**Comment by remo7777** [comment]
hey bro good news for UFOnet tool.. all dependency available now..

**Comment by remo7777** [comment]
![screenshot_2018-07-26-02-18-29-115_com termux](https://user-images.githubusercontent.com/28594846/43226868-a67daa82-907a-11e8-9fc4-a78bb2158294.png)
