### ISSUE TITLE
sqlokmap and zones 

### ISSUE THREAD

**Issue by neeransh** [Gameye98/Lazymux#10]
What are the GitHub I'd and password??

**Comment by Buzzkillhardball667** [comment]
You give them your login info for github. It will install after you do so

**Comment by neeransh** [comment]
It is saying no repositories found

**Comment by neeransh** [comment]
Also Kali nethuner is not updating.....show some repositories error.....but I checked the source and it is correct.....it can't even find python package

**Comment by neeransh** [comment]
root@localhost:~# apt-get update
Get:1 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease [30.5 kB]
Err:1 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: GPG error: http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@localhost:~#

**Comment by Gameye98** [comment]
The sqlokmed and zones repository has been removed by the author...
