### ISSUE TITLE
I can't find the files I'm downloading

### ISSUE THREAD

**Issue by AK4GAMES** [Gameye98/Lazymux#104]
![IMG_20220505_141136](https://user-images.githubusercontent.com/93545368/166939572-cc0e007b-76d5-44c9-a105-385ac7270be7.jpg)

**Comment by Gameye98** [comment]
Are u blind? Just type:
$ proot-distro login fedora

**Comment by AK4GAMES** [comment]
> 

 I don't wanna open fedora
I need fedora file

**Comment by Gameye98** [comment]
/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
