### ISSUE TITLE
Kali NetHunter is not updating

### ISSUE THREAD

**Issue by neeransh** [Gameye98/Lazymux#11]
root@localhost:~# apt-get update
Get:1 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease [30.5 kB]
Err:1 http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: GPG error: http://ftp.yzu.edu.tw/Linux/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'http://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@localhost:~#

**Comment by T4P4N** [comment]
Ask Hax4us !

**Comment by DolphinChips** [comment]
You just forgot to add repo's key. Always read README.md first.

**Comment by Gameye98** [comment]
Ask directly to **Hax4US**
