### ISSUE TITLE
konfigurasi yang tepat untuk folder instalasi

### ISSUE THREAD

**Issue by rendykyh** [Gameye98/Lazymux#117]
bagaimana cara edit file lazymux.conf yang benar ya bang?
saya ingin memindahkannya kesini...
Home = $PREFIX/opt

**Comment by Gameye98** [comment]
HOME = $PREFIX/opt

**Comment by z4rathustr4** [comment]
Can't get it to work, my lazymux.conf is located at ~/lazymux.conf and I keep editing it, I tried with TOML syntax as the original file generated by the script was TOML, but I've also tried as stated here, without the square brackets. None of that works. Keeps cloning repos at ~/sqlmap (e.g).
Could it be some type of mishandling the hardcoded config and the actual file that's created in $HOME? (~/lazymux.conf).
I think I've tried everything, help would be appreciated.
Thanks in advance.

**Comment by Gameye98** [comment]
> Can't get it to work, my lazymux.conf is located at ~/lazymux.conf and I keep editing it, I tried with TOML syntax as the original file generated by the script was TOML, but I've also tried as stated here, without the square brackets. None of that works. Keeps cloning repos at "$HOME/sqlmap" (e.g). Could it be some type of mishandling the hardcoded config and the actual file that's created in $HOME? ($HOME/lazymux.conf"). I think I've tried everything, help would be appreciated. Thanks in advance.

---
It will only follow the configuration on the directory of Lazymux
So its only follow the lazymux.conf from the current Lazymux directory, so even if u make copied version the $HOME/lazymux.conf it will be ignored :)
