### ISSUE TITLE
Cannot link executable

### ISSUE THREAD

**Issue by minecraftman781** [Gameye98/Lazymux#118]
There's a screenshot of this issue![Screenshot_20220907_120854_com.termux.jpg](https://user-images.githubusercontent.com/52201291/188839163-be5530f3-c818-40e9-85f3-cf92a5d115b5.jpg)

**Comment by ret7020** [comment]
This is not an issue of lazymux. This is an issue in git. You have to install openssl.
Try this command:
`pkg install openssl-1.1`
