### ISSUE TITLE
User and password 

### ISSUE THREAD

**Issue by shiv12300** [Gameye98/Lazymux#119]

**Comment by pussyknit** [comment]
What

**Comment by mrkaran777** [comment]
What is username and password 😵‍💫

**Comment by vanjusa** [comment]
Username for 'https://github.com':?????
Password for 'https://
![IMG_20221016_135728](https://user-images.githubusercontent.com/115928455/196034150-86a3bedb-0ccd-488e-8989-7033dcd289a4.jpg)

**Comment by Ashiq899** [comment]
Username or password?

**Comment by Sd-Shiivam** [comment]
it's your GitHub username and password asking to login in terminal. before cloning the repo, you have to login that's why it is asking for your username and password.
