### ISSUE TITLE
Can't install multi tools and all tools 

### ISSUE THREAD

**Issue by UnkownPlayerX000** [Gameye98/Lazymux#125]
So I cloned the repositry and did what you said in the read.me but when I type 1 2 3 4 and so on it says wrong input even tried 01 02 03 04 and so on its still the same and also happens with @

**Comment by Methods101** [comment]
hey i just looked at the code by this guy and i realised if you go to one of the categories and put @ it will start downloading all the tools. So just go to every category and put @ like this:

`Install All Tool`
lzmx > set_install @

**Comment by Gameye98** [comment]
> hey i just looked at the code by this guy and i realised if you go to one of the categories and put @ it will start downloading all the tools in that category. So just go to every category and put @ like this:
> 
> 
> 
> `Install All Tool`
> 
> lzmx > set_install @

thank u for taking my place answer the question
