### ISSUE TITLE
metasploit isn't added to the repo list before installing 

### ISSUE THREAD

**Issue by williambarasa** [Gameye98/Lazymux#128]
So, I was using lazymux right? And I try to install metasploit but they did not added metaspoit to the repo list before installing. 
Metasploit isn't on the repo list so when you 
pkg/apt install metasploit, it won't work. And, it says "Done" but the packages didn't install. ![Screenshot_20231109_172855_Termux.jpg](https://github.com/Gameye98/Lazymux/assets/100489181/aa37a4a8-8f13-48e5-ad8c-c7da8f1c59cc)

But don't worry! There's a simple solution.
""curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
  chmod 755 msfinstall && \
  ./msfinstall""

**Comment by Gameye98** [comment]
now it could install metasploit.
