### ISSUE TITLE
another error ---- how to solve? 

### ISSUE THREAD

**Issue by darkKnight-8** [Gameye98/Lazymux#129]
File "/home/elnemr/Lazymux/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/home/elnemr/Lazymux/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
              ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Gameye98** [comment]
U should run with python3 which in termux the package name is python

dont run with python2
