### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by SeifAjax04** [Gameye98/Lazymux#130]
git clone https://github.com/Gameye98/Lazymux.git 

1-|  ls 

2-|  cd Lazymux 

3-|  ls 

4-|   chmod +x  lazymux.py 

5-|  python3 lazymux.py

steps I've taken but this msg. shown:

Traceback (most recent call last):
  File "/home/Tools/Lazymux/lazymux.py", line 6, in <module>
    from core.lzmcore import *
  File "/home/Tools/Lazymux/core/lzmcore.py", line 26, in <module>
    cache_1 = prefix+"/tmp/lazymux_1"
              ~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by pussyknit** [comment]
It's a Yung syntax error to keep assholes from using these tools for
malicious intent. Following the basic rules for command line to switch
files to allow them to become executable. If you don't see error you
clearly don't have the basic knowledge and therefore must figure it out in
your own. I will not be responsible for misuse of this pentesting
environment sorry and thank you for reaching out. I have given you the
secret formula for Kelloggs frosted flakes you must decipher this error to
gain access to the magic kingdom of fruity and delicious tits. Also try
python3.py and python2.py through process of trail and error one can truly
find happiness... In short, don't let your meatloaf my brother.

**Comment by pussyknit** [comment]
Get it? You'll figure it out I just can't give you the answer as that would
be unethical.

**Comment by pussyknit** [comment]
Try     ( python2 lazymux. py) without the () brackets

**Comment by Gameye98** [comment]
Lazymux could only run in termux using python 3 which in termux the package name is python, it following python 3 syntax and thats why python2 cant read or execute it

```bash
$ apt install python
$ python lazymux.py
```
