### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by basu021** [Gameye98/Lazymux#20]
> Lazymux.apk  README.md  app  core  lazymux.py
$ python lazymux.py
  File "lazymux.py", line 11
    print "   [01] Information Gathering"
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("   [01] Information Gathering")?
$ 1
No command 1 found, did you mean:
 Command [ in package coreutils
 Command k in package kona
 Command v in package vlang from the unstable-repo repository
$ python lazymux.py
  File "lazymux.py", line 11
    print "   [01] Information Gathering"
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("   [01] Information Gathering")?
$

**Comment by Gameye98** [comment]
Make sure you're read the README.md
Run Lazymux with python2 ( python2.x)

$ apt install python2
$ python2 lazymux.py

**Comment by TermuxGoat** [comment]
It still  happening

**Comment by Gameye98** [comment]
Could you provide a screenshot?

**Comment by Gameye98** [comment]
If you face the same issue with the one who open issue, you just need to install python 3 and run lazymux with it.

**Comment by TermuxGoat** [comment]
Nevermind I fixed it thanks tho
