### ISSUE TITLE
No coomands

### ISSUE THREAD

**Issue by seth7799** [Gameye98/Lazymux#24]
I canto tudo no Colman

**Comment by Gameye98** [comment]
What are you sayin, i dont understand?

**Comment by Gamer-dot** [comment]
Bro @Gameye98 theres no command in lazymux

> #

**Comment by Gameye98** [comment]
If you mean, you dont know how to install Lazymux, you need to read the installation step on README.md

**Comment by Gamer-dot** [comment]
@Gamer-dot  i know how to install but there's no commands really I'm not lying to you dude no commands

**Comment by Gameye98** [comment]
do you mean you dont know how to run?

**Comment by Sahraoui1** [comment]
When I choose  numbre 6 

lzmx > 6
Traceback (most recent call last):
  File "lazymux.py", line 484, in <module>
    main()
  File "lazymux.py", line 28, in main
    if lazymux.strip() == "1" or lazymux.strip() == "01":
AttributeError: 'int' object has no attribute 'strip'

**Comment by Gameye98** [comment]
execute lazymux with python 3

by typing

```
python lazymux.py
```
