### ISSUE TITLE
Lazymux

### ISSUE THREAD

**Issue by nitin453** [Gameye98/Lazymux#27]
My lazymux is not working
![Screenshot_20200412-185517_ConnectBot](https://user-images.githubusercontent.com/63289057/79069863-32d3f100-7cef-11ea-80a1-af0649fc6f20.jpg)

**Comment by jenish2811** [comment]
Same issue fr me also

**Comment by Gameye98** [comment]
Consider to run Lazymux with python 3 version
Which in termux you gotta do this way

python lazymux.py

Please next time for open issue, you need to provide the error log or screenshot of it
