### ISSUE TITLE
Lazymux tidak jalan

### ISSUE THREAD

**Issue by harie112** [Gameye98/Lazymux#34]
bash-5.0$ python lazymux.py
  File "lazymux.py", line 380
SyntaxError: Non-UTF-8 code starting with '\xae' in file lazymux.py on line 380, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
bash-5.0$

**Comment by Gameye98** [comment]
jalankan lazymux dengan python 3
masukkan perintah ini di termux:

python lazymux.py
