### ISSUE TITLE
Alguna solución?

### ISSUE THREAD

**Issue by HaroldLimad** [Gameye98/Lazymux#35]
![Screenshot_20200521-130755](https://user-images.githubusercontent.com/64943687/82591079-6151b100-9b64-11ea-823a-88b95803c3c8.jpg)

**Comment by Gameye98** [comment]
You can update the Lazymux, its have been fixed
```
$ cd $HOME/Lazymux
$ git pull
```

**Comment by HaroldLimad** [comment]
Thanks brother
