### ISSUE TITLE
Meta install

### ISSUE THREAD

**Issue by royrey** [Gameye98/Lazymux#4]
$cd Lazymux
$ ls
README.md   core        lazymux.py

Why there is not meta-install.sh ?

**Comment by incognitoprogrammer** [comment]
Have you found the FIX for this?!

**Comment by incognitoprogrammer** [comment]
Ive got lazymux the script itself to work by using"$python2 lazymux.py". But still cant figure out how to update it... Any help wpuld be greatly appreciated, thank you.

**Comment by Gameye98** [comment]
Hi,

about the meta-install script ... I've made updates on the script meta-install.sh, msfinstall. (https://gist.github.com/Gameye98/d31055c2d71f2fa5b1fe8c7e691b998c)

**Comment by termux4me** [comment]
Hi Lazymux
The download link of Lazymux isn't working
http://girhub.com/Gameye98/Lazymux.git
