### ISSUE TITLE
make sure your device has been rooted

### ISSUE THREAD

**Issue by Gildur7161** [Gameye98/Lazymux#42]
Hi,
I have an error when trying to install a tool. It says

> ERROR: Make sure you're device has been rooted

But I can't even start it when in su, and it does not ask for root permissions (termux already did)

Thanks

**Comment by Gameye98** [comment]
Does your phone has been root?
If it does, run tsu command on your termux before run Lazymux

**Comment by Gildur7161** [comment]
Ok so tsu worked, but I have no idea where it has been saved

**Comment by Gameye98** [comment]
$ pkg up -y
$ apt install tsu -y

**Comment by Gildur7161** [comment]
I was talking about the module installed from lazymux. Sorry about that

**Comment by Gameye98** [comment]
What module you have install on your termux?

**Comment by Gildur7161** [comment]
it's a fresh install, almost nothing...

**Comment by Gameye98** [comment]
Pls provide any screenshot... cuz i dont understand what kind of issues you have when runnin Lazymux

**Comment by Gildur7161** [comment]
![Screenshot_20200727-110839](https://user-images.githubusercontent.com/24982486/88524543-c361e300-cff9-11ea-8587-4be01721e80a.jpg)
Alright here is what I have (fresh install)
And if I try to run it with su:
![Screenshot_20200727-111128](https://user-images.githubusercontent.com/24982486/88524749-0a4fd880-cffa-11ea-9451-bc1c686f8b19.jpg)
Now with tsu: 
![Screenshot_20200727-111323](https://user-images.githubusercontent.com/24982486/88524884-39fee080-cffa-11ea-8659-9eb0fd86c26d.jpg)
As you can see, tsu make it cloning the git, but I have absolutely no clue from where it is saved

**Comment by Gameye98** [comment]
If you check on the lzmcore.py  
It always move the cloned project into the `$HOME`  
Where the symbol of ~ is refer the home directory, could you show me your current directory by input `pwd` on your termux and send a new screenshot?  
And try to check your home directory by enter this command...

```bash
ls $HOME
```

**Comment by Gildur7161** [comment]
![Screenshot_20200727-195101](https://user-images.githubusercontent.com/24982486/88574372-8e2db300-d042-11ea-8065-0e2e825491c4.jpg)
There you go

**Comment by domdroid9944** [comment]
@Gameye98

**Comment by Gameye98** [comment]
Could you send a screenrecord to me when installing wifite with Lazymux? Cause there's no error on the code...

**Comment by Gildur7161** [comment]
Ok so I was recording it for no reasons this time it has been saved in the Lazymux directory...BUT while trying to run it, turns out it need python 2 to work. Any advice on how to install 2 versions of python?

**Comment by Gameye98** [comment]
I think the previous wifite has been saved to $HOME/.suroot

Solved!!
