### ISSUE TITLE
Change default install directory & install multiple tools at once

### ISSUE THREAD

**Issue by scndthe2nd** [Gameye98/Lazymux#51]
Hi,

Great tool, I love it. 

I'd like to change my default install directory. Is there a way for me to do this in like a config file?

I'd also like to select multiple items, or all items in a category and have them install. Is there a way to do this?

Sorry, I'm still learning, and thanks for the help

**Comment by Gameye98** [comment]
Thanks for your feedback, i'll do my best to add config file (default install directory) and select multiple items in list

**Comment by Gameye98** [comment]
It has been updated.

**Comment by scndthe2nd** [comment]
Thanks
