### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by nis130** [Gameye98/Lazymux#6]
I got an syntax error when tried to open in termux emulator for Android 
![screenshot_20180312-185007](https://user-images.githubusercontent.com/35602510/37285874-693a6f0c-2626-11e8-8e1c-c8f13fb3c1dd.jpeg)

**Comment by WyattWade604** [comment]
This is due to a code error! What you need to do is put parentheses around the print statement! Such as: 
`print ("Hey there!")` This needs to go on every command to print.

**Comment by WyattWade604** [comment]
Use `pkg install nano`. This will install a terminal text and code editor. Then use a keyboard on your phone that has CTRL and FN this will allow you to save the edits. Then use `nano lazymux.py` and you can begin editing. After you can save it and start the program! Use `python laxymux.py`!
```md
(Did I help?)[Yes? No?!]
```

**Comment by Gameye98** [comment]
Execute the script with python2

Install it by typing

apt-get install python2

**Comment by king1lab** [comment]
![Screenshot_20210122-095054](https://user-images.githubusercontent.com/75205870/105468530-5e7d0200-5c97-11eb-9ff4-f27eabf42766.png)

**Comment by king1lab** [comment]
am getting 32bit instead of 64bit error

**Comment by msrakendry** [comment]
$ ls
Lazymux      README.md  core        lazymux.py
Lazymux.apk  app        lazymux.db  set_install
$ python2 lazymux.py
  File "lazymux.py", line 75
    infogathering += f"{x} "
                           ^
SyntaxError: invalid syntax
I need help,.

**Comment by anon666exp3rt** [comment]
> ```lisp
> No
> ```

How to fix

**Comment by Gameye98** [comment]
Now Lazymux has been updated to Python 3

So, run by typing below command on your termux :)
`python lazymux.py`
