### ISSUE TITLE
Syntax Error line 73

### ISSUE THREAD

**Issue by Jayjigz** [Gameye98/Lazymux#61]
python lazymux.py                                                      
  File "lazymux.py", line 73                          
    infogathering += f"{x} "                          
                                          ^                          
SyntaxError: invalid syntax

**Comment by Jayjigz** [comment]
![2FB3E308-2930-4AF5-8CC2-26B0A71FBC03](https://user-images.githubusercontent.com/40969742/97808731-7437e800-1ca3-11eb-9068-90638bdb54d2.jpeg)

**Comment by Gameye98** [comment]
Run lazymux.py script with Python 3.x not Python 2.x

I think you're not run lazymux from termux...
python in termux is Python 3.x
python2 in termux is Python 2.x

**Comment by rutik228** [comment]
I can't help you

**Comment by Jayjigz** [comment]
![image](https://user-images.githubusercontent.com/40969742/97955483-3b9e2880-1de1-11eb-93af-3f5c4f825fb1.jpeg)

**Comment by Gameye98** [comment]
`python lazymux.py`

*NOT*

`python2 lazymux.py`

**Comment by honzo666-c** [comment]
hey i broke my phone...but maybe you can help me with my cromebook with
installing wine or am application for running python1/2 for app development
