### ISSUE TITLE
I cant run it...could you help me?

### ISSUE THREAD

**Issue by blisszard-08** [Gameye98/Lazymux#63]
Well...i downloaded lazymux followed all the steps but it for some reason doesnt work.
It says: python: can't open file '/data/data/com.termux/files/home/Lazymux/Lazymux.py': [Errno 2] No such file or directory.
I checked every step and im not doing anything wrong(i guess)
Sry if its a stupid mistake, i downloaded termux and started learning how to use it today

**Comment by Gameye98** [comment]
You need to enter Lazymux directory then type:
$ python lazymux.py

No single uppercase letter contain in the filename.

**Comment by blisszard-08** [comment]
Ohh ok
