### ISSUE TITLE
Syntax error line 77

### ISSUE THREAD

**Issue by LAZY-VAMPIRE** [Gameye98/Lazymux#75]
I get this message while running the Lazymux

![Screenshot_2021-04-19-11-20-10-771_com termux](https://user-images.githubusercontent.com/82246674/115187811-97473e80-a101-11eb-8479-5c36bca67055.jpg)

**Comment by Gameye98** [comment]
Run with Python 3.x

Install Python 3 on termux
```bash
pkg up -y
apt install python
```
Run lazymux.py
`python lazymux.py`

**Comment by Habibmostafa2002** [comment]
Hi dear will you have error in your tools installing languish python 2 and
try again good luck

بتاريخ ٢٠٢١/٠٤/١٩ ١:١٢ م، كتب "DedSecTL" ***@***.***>:
