### ISSUE TITLE
I want to use it on Ubuntu environment but getting error

### ISSUE THREAD

**Issue by LAZY-VAMPIRE** [Gameye98/Lazymux#77]
![Screenshot_2021-04-24-17-26-28-639_com termux](https://user-images.githubusercontent.com/82246674/115957840-695b6300-a522-11eb-973a-410c27a59e9d.jpg)

**Comment by Gameye98** [comment]
Are you using Lazymux from Sanix-Darker??

**Comment by addd215** [comment]
me too

**Comment by LAZY-VAMPIRE** [comment]
Yes

**Comment by Gameye98** [comment]
If its still running an error on the Sanix-Darker/Lazymux then i can't help...
Cuz Lazymux made specially for termux environment :)
