### ISSUE TITLE
- Filesize:1495026 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### ISSUE THREAD

**Issue by Koushikk900** [Gameye98/Lazymux#80]
**How can i solve this problem ** ?

~ $ ls
EasY_HaCk-results  Lazymux  storage
~ $ cd Lazymux
~/Lazymux $ ls
README.md  core  lazymux.db  lazymux.py
~/Lazymux $ python lazymux.py
The program python is not installed. Install it by executing:
 pkg install python
~/Lazymux $ pkg install python
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  binutils clang gdbm glib libllvm make
  ncurses-ui-libs ndk-sysroot pkg-config
Suggested packages:
  python-tkinter
The following NEW packages will be installed:
  binutils clang gdbm glib libllvm make
  ncurses-ui-libs ndk-sysroot pkg-config python
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 1495 kB/52.0 MB of archives.
After this operation, 320 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://dl.kcubeterm.me/termux-packages-24 stable/main aarch64 ndk-sysroot aarch64 21d-1 [1495 kB]
Err:1 https://dl.kcubeterm.me/termux-packages-24 stable/main aarch64 ndk-sysroot aarch64 21d-1
  File has unexpected size (1490842 != 1495026). Mirror sync in progress? [IP: 104.21.11.101 443]
  Hashes of expected file:
   - SHA512:6708b082d19bbbd2df8d29cb4e9fe59877cdbeb43de1e1eec1230bee74fde75cc8de6c42b381b988929756c6cb84598327a0a6d4804207df15e89a0c30cfe956
   - SHA256:480534d358250b01fbaf5f72053aa58e86fe330c315fc2cdad8d92a0b6ee7194
   - SHA1:1476018252e6b5fbf04d0dac04f018e88a85d725 [weak]
   - MD5Sum:52d663ee2ef00af71e7637dd586d4b17 [weak]
   - Filesize:1495026 [weak]
E: Failed to fetch https://dl.kcubeterm.me/termux-packages-24/pool/main/n/ndk-sysroot/ndk-sysroot_21d-1_aarch64.deb  File has unexpected size (1490842 != 1495026). Mirror sync in progress? [IP: 104.21.11.101 443]
   Hashes of expected file:
    - SHA512:6708b082d19bbbd2df8d29cb4e9fe59877cdbeb43de1e1eec1230bee74fde75cc8de6c42b381b988929756c6cb84598327a0a6d4804207df15e89a0c30cfe956
    - SHA256:480534d358250b01fbaf5f72053aa58e86fe330c315fc2cdad8d92a0b6ee7194
    - SHA1:1476018252e6b5fbf04d0dac04f018e88a85d725 [weak]
    - MD5Sum:52d663ee2ef00af71e7637dd586d4b17 [weak]
    - Filesize:1495026 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
~/Lazymux $__![Screenshot_20210612_070520.jpg](https://user-images.githubusercontent.com/81311798/121761276-7ffa5f80-cb4c-11eb-983f-33b9c609cc97.jpg)__

**Comment by Gameye98** [comment]
Its not an error generated from Lazymux...
It seems like the repo having trouble to sync or verify the package based on the size and hashes.
The file checksum is different from the expected checksum, so its identified as corrupted file.
