### ISSUE TITLE
Zip.

### ISSUE THREAD

**Issue by Batuhanrortos** [Gameye98/Lazymux#90]
Hocam instahack kısmında zip dosyasıni indirin demişsiniz de o dosyayı nereden indireceğim? O şifre ve elite proxyleri nereden alacağım? Yardımcı olursanız sevinirim.

**Comment by Gameye98** [comment]
Temel Linux komutlarını öğrenin ve her zaman görünen hata mesajlarına dikkat edin.  En azından ne yaptığınıza dair temel bir anlayışa sahip olmanız ve İngilizce konuşabilmeniz gerekir çünkü bilgisayar korsanlığı araçlarının çoğu İngilizce yazılmış bir ekran içerir.
