### ISSUE TITLE
I don't know what's wrong can anyone help me

### ISSUE THREAD

**Issue by AJK000** [Gameye98/Lazymux#92]
$ python2 lazymux.py
  File "lazymux.py", line 86
    infogathering += f"{x} "
                           ^
SyntaxError: invalid syntax

**Comment by mathews52gb** [comment]
$ python2 lazymux.py
File "lazymux.py", line 86
infogathering += f"{x} "
^
SyntaxError: invalid syntax

Same error

**Comment by AJK000** [comment]
I guess it's a error in the script

**Comment by zal-byte** [comment]
This script need python3.x version

**Comment by AJK000** [comment]
How can i do it
